
[font]
size = 10
[font.normal]
family = "VictorMono Nerd Font"
style = "Bold"

[window]
blur = true
decorations_theme_variant = "Dark"
opacity = 0.9
padding = { x = 4, y = 4 }

[shell]
program = "/usr/bin/fish"

[colors]
[colors.bright]
black = "0x6e7681"
blue = "0x79c0ff"
cyan = "0x39c5cf"
green = "0x79c0ff"
magenta = "0xbc8cff"
red = "0xfdac54"
white = "0xb1bac4"
yellow = "0xe3b341"

[colors.cursor]
cursor = "0xc9d1d9"
text = "0x0d1117"

[colors.normal]
black = "0x484f58"
blue = "0x58a6ff"
cyan = "0x39c5cf"
green = "0x58a6ff"
magenta = "0xbc8cff"
red = "0xec8e2c"
white = "0xb1bac4"
yellow = "0xd29922"

[colors.primary]
background = "0x0d1117"
foreground = "0xc9d1d9"
