#!/usr/bin/env zsh
# bsp pr float
yabai -m config layout bsp

# padding
yabai -m config top_padding 10
yabai -m config bottom_padding 10
yabai -m config left_padding 10
yabai -m config right_padding 10
yabai -m config window_gap 10

# auto balance
yabai -m config auto_balance off

# shadow in float
yabai -m config window_shadow float

# opacity
yabai -m config window_opacity off
yabai -m config active_window_opacity 1.0
yabai -m config normal_window_opacity 0.8

# config external bar
SPACEBAR_HEIGHT=$(spacebar -m config height)
yabai -m config external_bar all:26:0

# rules
yabai -m rule --add app="^(Preferencias|Preferences)$" manage=off
